# -*- coding: utf-8 -*-
"""edusalary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CSscQm0yn7QWzDB9g00APxFGMxHWureG
"""

import pickle
import numpy as np

# Load the model
with open('kaggle_edu_model_2025 (1).pkl', 'rb') as file:
    model = pickle.load(file)

def predict_salary(features):
    """
    Predict salary based on input features.
    Args:
        features (list or np.array): The input features expected by the model.

    Returns:
        float: Predicted salary.
    """
    features = np.array(features).reshape(1, -1)
    prediction = model.predict(features)
    return prediction[0]

def main():
    print("Salary Prediction App")
    print("Please provide the following inputs:")

    # Example of three features: years of experience, education level, and age
    try:
        years_experience = float(input("Years of Experience: "))
        education_level = float(input("Education Level (e.g., 1=Bachelor, 2=Master, 3=PhD): "))
        age = float(input("Age: "))

        # You might need to adjust the order and number of inputs based on your model
        features = [years_experience, education_level, age]

        salary = predict_salary(features)
        print(f"\nPredicted Salary: ${salary:,.2f}")
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()